"""PdfDocument repository — CRUD + queries. Isolates services from ORM."""

# TODO: implement when DB layer lands.
# class PdfRepository:
#     def __init__(self, session: AsyncSession) -> None: ...
#     async def create(self, ...) -> PdfDocument: ...
#     async def get(self, pdf_id: UUID) -> PdfDocument | None: ...
#     async def list_by_stage(self, stage: ProjectStage) -> list[PdfDocument]: ...
#     async def mark_ocr_done(self, pdf_id: UUID) -> None: ...
#     async def soft_delete(self, pdf_id: UUID) -> None: ...
