"""RefreshToken repository — rotate + revoke."""

# TODO: implement.
# async def create(user_id, token_hash, expires_at, ua, ip) -> RefreshToken: ...
# async def get_active_by_hash(token_hash) -> RefreshToken | None: ...
# async def rotate(current_id, new_hash, expires_at) -> RefreshToken: ...
# async def revoke(token_id) -> None: ...
# async def revoke_all_for_user(user_id) -> None: ...
