"""User repository — CRUD + queries."""

# TODO: implement.
# async def get_by_email(email: str) -> User | None: ...
# async def create(email, password_hash, full_name, role) -> User: ...
# async def update_last_login(user_id, at) -> None: ...
