"""Arq job handlers — one function per background job.

Each handler receives `ctx` (Arq context: redis, job_id, retries) + job kwargs.
Emit progress via `event_bus.publish(channel, event, payload)` so frontend WS gets updates.
"""

# TODO: implement each handler.
#
# async def ingest_pdf(ctx, file_id: str) -> None: ...
# async def run_ocr(ctx, file_id: str) -> None: ...
# async def extract_elements(ctx, file_id: str) -> None: ...
# async def classify_stage(ctx, file_id: str) -> None: ...
# async def chunk_and_embed(ctx, file_id: str) -> None: ...
# async def run_validation(ctx, file_id: str, stage: str) -> None: ...
# async def generate_report(ctx, report_id: str) -> None: ...
# async def send_email(ctx, to: str, subject: str, body: str) -> None: ...
# async def dispatch_push(ctx, user_id: str, title: str, body: str) -> None: ...
