import { useState } from "react";
import { EdifiShell } from "@/shared/components/layout/edifice-shell";
import { EdIcon } from "@/shared/icons/edifice-icons";

export function SaAdminReportsPage() {
  const [schedules, setSchedules] = useState([true, true, true]);
  const toggle = (i: number) => setSchedules((s) => s.map((v, idx) => (idx === i ? !v : v)));

  return (
    <>
      <style>{`
    .toggle-switch { width: 36px; height: 20px; border-radius: 10px; background: var(--color-gray-200); position: relative; cursor: pointer; transition: background 0.2s; }
    .toggle-switch.active { background: var(--color-green-500); }
    .toggle-switch::after { content: ''; position: absolute; top: 2px; left: 2px; width: 16px; height: 16px; border-radius: 50%; background: white; transition: transform 0.2s; box-shadow: var(--shadow-sm); }
    .toggle-switch.active::after { transform: translateX(16px); }
      `}</style>
      <EdifiShell system="site-agent" activeNav="reports" section="admin">
        <div className="page-header">
          <h1>Report Configuration</h1>
          <p>Configure report templates, branding, and scheduled report automation.</p>
        </div>

        {/* Templates */}
        <div className="card p-6 mb-6">
          <div className="section-header"><span className="section-title">Report Templates</span><button className="btn btn-ghost btn-sm"><EdIcon name="plus" size={12} /> Create Template</button></div>
          <div className="grid-3" style={{ gap: "1rem" }}>
            <div className="card card-flat p-5" style={{ cursor: "pointer" }}>
              <div style={{ color: "var(--color-blue-500)", marginBottom: "0.75rem" }}><EdIcon name="calendar" size={24} /></div>
              <h4 style={{ fontSize: "0.9375rem", fontWeight: 700, marginBottom: "0.25rem" }}>Daily Site Report</h4>
              <p style={{ fontSize: "0.75rem", color: "var(--color-gray-400)" }}>Observations by floor, photos, and severity.</p>
              <div className="flex gap-2 mt-3"><span className="badge badge-green" style={{ fontSize: "0.5625rem" }}>Active</span><span className="badge badge-gray" style={{ fontSize: "0.5625rem" }}>Branded</span></div>
            </div>
            <div className="card card-flat p-5" style={{ cursor: "pointer" }}>
              <div style={{ color: "var(--color-amber-500)", marginBottom: "0.75rem" }}><EdIcon name="barChart" size={24} /></div>
              <h4 style={{ fontSize: "0.9375rem", fontWeight: 700, marginBottom: "0.25rem" }}>Weekly Summary</h4>
              <p style={{ fontSize: "0.75rem", color: "var(--color-gray-400)" }}>Aggregated stats, trends, and resolution rates.</p>
              <div className="flex gap-2 mt-3"><span className="badge badge-green" style={{ fontSize: "0.5625rem" }}>Active</span></div>
            </div>
            <div className="card card-flat p-5" style={{ cursor: "pointer" }}>
              <div style={{ color: "var(--color-red-500)", marginBottom: "0.75rem" }}><EdIcon name="clipboardList" size={24} /></div>
              <h4 style={{ fontSize: "0.9375rem", fontWeight: 700, marginBottom: "0.25rem" }}>Snag List</h4>
              <p style={{ fontSize: "0.75rem", color: "var(--color-gray-400)" }}>Open issues with photos and action items.</p>
              <div className="flex gap-2 mt-3"><span className="badge badge-green" style={{ fontSize: "0.5625rem" }}>Active</span><span className="badge badge-gray" style={{ fontSize: "0.5625rem" }}>External</span></div>
            </div>
          </div>
        </div>

        {/* Branding */}
        <div className="card p-6 mb-6">
          <span className="section-title">Report Branding</span>
          <div className="grid-2 mt-4" style={{ gap: "1.5rem" }}>
            <div>
              <div className="form-group"><label className="form-label">Company Name</label><input className="form-input" defaultValue="Edifice Architects" /></div>
              <div className="form-group"><label className="form-label">Report Header Text</label><input className="form-input" defaultValue="Site Observation Report" /></div>
              <div className="form-group"><label className="form-label">Footer Disclaimer</label><textarea className="form-input form-textarea" style={{ minHeight: "60px", borderRadius: "var(--radius-xl)" }} defaultValue="This report is auto-generated by Edifice AI Automation. Data is based on site observations captured through the platform." /></div>
            </div>
            <div>
              <div className="form-group"><label className="form-label">Logo Upload</label><div className="upload-zone" style={{ padding: "2rem", borderRadius: "var(--radius-xl)" }}><div style={{ margin: "0 auto 0.5rem", color: "var(--color-gray-300)" }}><EdIcon name="upload" size={24} /></div><p>Click or drag to upload logo</p></div></div>
              <div className="form-group"><label className="form-label">External Report Cover Color</label><select className="form-input form-select"><option>Dark — Black (#0a0a0a)</option><option>Navy (#1e3a5f)</option><option>Charcoal (#374151)</option></select></div>
            </div>
          </div>
        </div>

        {/* Scheduled Reports */}
        <div className="card p-6">
          <span className="section-title">Automated Schedules</span>
          <div className="mt-4">
            <div className="flex items-center justify-between py-3 border-b">
              <div><strong style={{ fontSize: "0.875rem" }}>Daily Report — All Projects</strong><br /><span style={{ fontSize: "0.6875rem", color: "var(--color-gray-400)" }}>Sent to: sethi@edifice.com, sharma@edifice.com</span></div>
              <div className="flex items-center gap-3"><span style={{ fontSize: "0.75rem", color: "var(--color-gray-400)" }}>Every day at 6:00 PM</span><div className={`toggle-switch ${schedules[0] ? "active" : ""}`} onClick={() => toggle(0)}></div></div>
            </div>
            <div className="flex items-center justify-between py-3 border-b">
              <div><strong style={{ fontSize: "0.875rem" }}>Weekly Summary — All Projects</strong><br /><span style={{ fontSize: "0.6875rem", color: "var(--color-gray-400)" }}>Sent to: management@edifice.com</span></div>
              <div className="flex items-center gap-3"><span style={{ fontSize: "0.75rem", color: "var(--color-gray-400)" }}>Monday at 9:00 AM</span><div className={`toggle-switch ${schedules[1] ? "active" : ""}`} onClick={() => toggle(1)}></div></div>
            </div>
            <div className="flex items-center justify-between py-3">
              <div><strong style={{ fontSize: "0.875rem" }}>Critical Alert — Immediate</strong><br /><span style={{ fontSize: "0.6875rem", color: "var(--color-gray-400)" }}>Sent to: all admins</span></div>
              <div className="flex items-center gap-3"><span style={{ fontSize: "0.75rem", color: "var(--color-gray-400)" }}>On critical observation</span><div className={`toggle-switch ${schedules[2] ? "active" : ""}`} onClick={() => toggle(2)}></div></div>
            </div>
          </div>
        </div>

        <div className="flex justify-end gap-3 mt-6"><button className="btn btn-secondary">Cancel</button><button className="btn btn-primary"><EdIcon name="check" size={14} /> Save Configuration</button></div>
      </EdifiShell>
    </>
  );
}
